name: StaffChat
author: Glenjendary
main: com.glenjendary.staffchat.main
version: 0.1
description: Toggle staffchat on and off rather then /sc [msg]
commands:
  staffchat:
    usage: /staffchat
    description: Use this to toggle Staff Chat ON or OFF!
    aliases: [sc, staffc, schat]
